-d C:\Users\khanh\Downloads\1_neuron_gowin\impl\gwsynthesis\1_neuron_gowin.vg
-p GW1N-1P5C-QFN48XF-7
-pn GW1N-UV1P5QN48XFC7/I6
-cst C:\Users\khanh\Downloads\1_neuron_gowin\src\1_neuron_gowin.cst
-cfg C:\Users\khanh\Downloads\1_neuron_gowin\impl\pnr\device.cfg
-sdc C:\Users\khanh\Downloads\1_neuron_gowin\src\1_neuron_gowin.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 10
-global_freq 50.000
